### ISSUE TITLE
multinode sample fails to boot on Apple Silicon

### ISSUE THREAD

**Issue by ianseyer** [JetBrains/teamcity-docker-samples#7]
Works fine on an intel mbp, but not my M1.

Fails with:
```

      <pre>jetbrains.buildServer.maintenance.exceptions.UnknownServerStartupError: Could not create the main application servlet: Unexpected exception parsing XML document from URL [jar:file:/opt/teamcity/webapps/ROOT/WEB-INF/lib/common-impl.jar!/META-INF/shared-agent-server-spring.xml]; nested exception is java.lang.IllegalStateException: Unable to load schema mappings from location [META-INF/spring.schemas]
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet$WebApplicationCreatorAndDestroyer.createApplication(TeamCityDispatcherServlet.java:3)
	at jetbrains.buildServer.maintenance.StartupProcessor.doApplicationStarting(StartupProcessor.java:767)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$1800(StartupProcessor.java:1455)
	at jetbrains.buildServer.maintenance.StartupProcessor$3.call(StartupProcessor.java:5)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:91)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:1524)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:549)
	at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:782)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:408)
	at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java:1)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [jar:file:/opt/teamcity/webapps/ROOT/WEB-INF/lib/common-impl.jar!/META-INF/shared-agent-server-spring.xml]; nested exception is java.lang.IllegalStateException: Unable to load schema mappings from location [META-INF/spring.schemas]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:414)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:126)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at jetbrains.buildServer.maintenance.WebDispatcherServlet.createWebApplicationContext(WebDispatcherServlet.java:28)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet$WebApplicationCreatorAndDestroyer.createApplication(TeamCityDispatcherServlet.java:7)
	at jetbrains.buildServer.maintenance.StartupProcessor.doApplicationStarting(StartupProcessor.java:767)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$1800(StartupProcessor.java:1455)
	at jetbrains.buildServer.maintenance.StartupProcessor$3.call(StartupProcessor.java:5)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:91)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:1524)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:549)
	at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:782)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:408)
	at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java:1)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by: java.lang.IllegalStateException: Unable to load schema mappings from location [META-INF/spring.schemas]
	at org.springframework.beans.factory.xml.PluggableSchemaResolver.getSchemaMappings(PluggableSchemaResolver.java:163)
	at org.springframework.beans.factory.xml.PluggableSchemaResolver.resolveEntity(PluggableSchemaResolver.java:112)
	at org.springframework.beans.factory.xml.DelegatingEntityResolver.resolveEntity(DelegatingEntityResolver.java:86)
	at org.springframework.beans.factory.xml.ResourceEntityResolver.resolveEntity(ResourceEntityResolver.java:74)
	at org.apache.xerces.util.EntityResolverWrapper.resolveEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.resolveDocument(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:126)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at jetbrains.buildServer.maintenance.WebDispatcherServlet.createWebApplicationContext(WebDispatcherServlet.java:28)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet$WebApplicationCreatorAndDestroyer.createApplication(TeamCityDispatcherServlet.java:7)
	at jetbrains.buildServer.maintenance.StartupProcessor.doApplicationStarting(StartupProcessor.java:767)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$1800(StartupProcessor.java:1455)
	at jetbrains.buildServer.maintenance.StartupProcessor$3.call(StartupProcessor.java:5)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:91)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:1524)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:549)
	at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:782)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:408)
	at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java:1)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by: java.net.MalformedURLException: no !/ found in url spec:file:/opt/teamcity/webapps/ROOT/WEB-INF/lib/spring-security.jar!/META-INF/spring.schemas
	at java.base/java.net.JarURLConnection.parseSpecs(JarURLConnection.java:172)
	at java.base/java.net.JarURLConnection.&lt;init&gt;(JarURLConnection.java:158)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.&lt;init&gt;(JarURLConnection.java:81)
	at java.base/sun.net.www.protocol.jar.Handler.openConnection(Handler.java:41)
	at java.base/java.net.URL.openConnection(URL.java:1099)
	at org.springframework.core.io.support.PropertiesLoaderUtils.loadAllProperties(PropertiesLoaderUtils.java:182)
	at org.springframework.beans.factory.xml.PluggableSchemaResolver.getSchemaMappings(PluggableSchemaResolver.java:154)
	at org.springframework.beans.factory.xml.PluggableSchemaResolver.resolveEntity(PluggableSchemaResolver.java:112)
	at org.springframework.beans.factory.xml.DelegatingEntityResolver.resolveEntity(DelegatingEntityResolver.java:86)
	at org.springframework.beans.factory.xml.ResourceEntityResolver.resolveEntity(ResourceEntityResolver.java:74)
	at org.apache.xerces.util.EntityResolverWrapper.resolveEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.resolveDocument(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:126)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at jetbrains.buildServer.maintenance.WebDispatcherServlet.createWebApplicationContext(WebDispatcherServlet.java:28)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet$WebApplicationCreatorAndDestroyer.createApplication(TeamCityDispatcherServlet.java:7)
	at jetbrains.buildServer.maintenance.StartupProcessor.doApplicationStarting(StartupProcessor.java:767)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$1800(StartupProcessor.java:1455)
	at jetbrains.buildServer.maintenance.StartupProcessor$3.call(StartupProcessor.java:5)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:91)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:1524)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:549)
	at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:782)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:408)
	at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java:1)
	at java.base/java.lang.Thread.run(Thread.java:829)
</pre>
  
  ```

**Comment by ianseyer** [comment]
On following boots, I get:
```

      <pre>java.lang.IllegalArgumentException: Wrong definition: "  int_id:                       vcs_root_int_id M      defines -- refers    TODO return refers when vcs_root table is populated".
	at jetbrains.buildServer.serverSide.db.schema.SchemaDefBuilder.buildTableDef(SchemaDefBuilder.java:244)
	at jetbrains.buildServer.serverSide.db.schema.SchemaDefBuilder.buildSchemaDef(SchemaDefBuilder.java:74)
	at jetbrains.buildServer.serverSide.db.DBSchema$1.call(DBSchema.java:58)
	at jetbrains.buildServer.serverSide.db.DBSchema$1.call(DBSchema.java:53)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at jetbrains.buildServer.util.concurrent.ConcurrentLazy.call(ConcurrentLazy.java:117)
	at jetbrains.buildServer.serverSide.db.DBSchema.getSchema(DBSchema.java:66)
	at jetbrains.buildServer.serverSide.db.DBSchema.generatePerSessionScript(DBSchema.java:365)
	at jetbrains.buildServer.maintenance.StartupProcessor$7.run(StartupProcessor.java:2)
	at jetbrains.buildServer.maintenance.StartupProcessor$7.run(StartupProcessor.java:3)
	at jetbrains.buildServer.serverSide.db.TeamCityDatabaseManager.connect(TeamCityDatabaseManager.java:583)
	at jetbrains.buildServer.maintenance.StartupProcessor.performConnectToDatabaseInternal(StartupProcessor.java:317)
	at jetbrains.buildServer.maintenance.StartupProcessor.performConnectToDatabase(StartupProcessor.java:430)
	at jetbrains.buildServer.maintenance.StartupProcessor.doDatabaseConnect(StartupProcessor.java:1081)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$800(StartupProcessor.java:1059)
	at jetbrains.buildServer.maintenance.StartupProcessor$3.call(StartupProcessor.java:3)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:91)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:1524)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:549)
	at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:782)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:408)
	at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java:1)
	at java.base/java.lang.Thread.run(Thread.java:829)
</pre>
  
  ```

**Comment by ilatypov** [comment]
Related: https://github.com/scireum/s3ninja/issues/174
